[build]
  publish = "."
  command = ""

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    preset = "desktop"

# Short links
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/@growsteadfast"
  status = 301
  force = true

[[redirects]]
  from = "/apply"
  to = "/contact.html#apply"
  status = 302

[[redirects]]
  from = "/waitlist"
  to = "/contact.html#waitlist"
  status = 302

[[redirects]]
  from = "/patreon"
  to = "https://patreon.com/"
  status = 301

# Pretty URLs
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/coaching"
  to = "/coaching.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

# 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
