
[build]
  publish = "."
  command = ""

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
    preset = "desktop"

[[redirects]] from = "/youtube" to = "https://www.youtube.com/@growsteadfast" status = 301
[[redirects]] from = "/apply"   to = "/contact.html#apply" status = 302
[[redirects]] from = "/waitlist" to = "/contact.html#waitlist" status = 302
[[redirects]] from = "/patreon" to = "https://www.patreon.com/YourPage" status = 301
